### PR TITLE
Allow dashes in toml keys

### PR DESCRIPTION
**Pull request by johannes-mueller**
According to the specs [1] dashes are allowed in bare keys

_____
[1] https://toml.io/en/v1.0.0-rc.3#keys

### CODE REVIEW

**Comment by johannes-mueller** [comment]
> @gongo could you please review or merge PRs?

@gongo, if you lack time to maintain this package any longer, I'd be willing to take over maintainership. It's crucial functionality to many people and it needs to be maintained.

**Comment by gongo** [comment]
Hi @johannes-mueller and @pkulev . Sorry for late reply 🙏

Thanks for good Pull Request!
But can you wait a little longer to merge this fix?

Currently, I'm also modifying `emacs-toml` with each release version of toml. (e.g. [0.2.0](https://github.com/gongo/emacs-toml/tree/support-toml_0_2_0))

**Comment by johannes-mueller** [comment]
Any news on these PRs? I would like to get a package into MELPA that depends on them.

**Comment by gongo** [comment]
@johannes-mueller Please let me know if there are any other pull requests you would like to see prioritized for merging.

**Comment by johannes-mueller** [comment]
> @johannes-mueller Please let me know if there are any other pull requests you would like to see prioritized for merging.

#6 and #8 are indeed important as they fix bugs.

**Pull request merged**
